### ISSUE TITLE
chimpX email subscription form

### ISSUE THREAD

**Issue by alyainec** [meltingmedia/chimpx#3]
HI,
i am trying to test a signup email using with your component and it does not work on me.

Here is my resource call for that snippet:

[[chimpxSubscribe? &formTpl=`mailchimpTPL` &successMsg=`Success`]]

my mailchimpTPL:

```
                <form action="[[~[[*id]]]]" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate">

                    <fieldset>
                        <label for="mc_EMAIL">Your Email</label>
                        <input type="text" value="" name="mc_EMAIL" class="required email" id="mc_EMAIL" />

                        <span>[[+MailChimp.success]][[+MailChimp.error]]</span>

                        <input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn" />
                    </fieldset>
                </form>
```

When i press the subscribe button, nothings happen. 
Please guide me again how to use this on a proper way.

Thanks

**Comment by rtripault** [comment]
Hi alyainec,

First, you would need to specify a list id to subscribe the users to (with &listId=`your list id here`).
Secondly, i would call the snippet uncached, since it have to process "dynamic" data.
Finally, if you want some information on what's going on, you might want to use &debug=`1`

Sorry for the lack of documentation, i plan to fix than (too) :)

**Comment by alyainec** [comment]
Hi  rtripault,

Sorry for the late reply. I follow your advise and it working! Thanks thanks very much for your help.

Forgive my little knowledge in MailChimp . 
When i first read the listId your reply, it was so very strange for me what this is for and where can i find it. Then i try to search on the internet and find this id on my mailchimp account.

I would like to suggest in the feature upgrade of Chimpx, that  you may include on "All your List TAB" the listId or unique ID so that it could be easier to find.

Thanks & more power to you.

**Comment by alyainec** [comment]
Hi rtripault,

I have another question, is there anyway to redirect the email subscription in another page after submit?

**Comment by rtripault** [comment]
alyainec,

Thanks for your suggestion about the list id, that will be in.
For the redirection, it's not possible in the current state of the snippet. but if you use FormIt hook (as posted in your other issue) your should be able to combine MailChimp hook & the redirect one (for some more documentation, please see :
http://rtfm.modx.com/display/ADDON/mChimpX
http://rtfm.modx.com/display/ADDON/FormIt.Hooks.redirect

Hope that will help :)
